# Generated by Django 4.2.4 on 2023-10-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(default="email", max_length=100),
        ),
    ]
