# Generated by Django 4.2.4 on 2023-09-11 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0003_task_task_created_task_task_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "TodoList"},
        ),
        migrations.AlterModelTable(
            name="task",
            table="task",
        ),
    ]
