# Generated by Django 4.2.4 on 2023-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-id"], "verbose_name": "TodoList"},
        ),
        migrations.AlterField(
            model_name="task",
            name="task_desc",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
