# Generated by Django 4.2.4 on 2023-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0006_alter_task_options_alter_task_task_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_desc",
            field=models.CharField(max_length=150),
        ),
    ]
